spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock2?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        session_factory:
          interceptor: com.mycompany.gestionstock.gestionDeStock.interceptor.Interceptor


    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8080


flickr:
  apiKey: ef92894a4cf93109133a676b59b7041e
  apiSecret: a76bceb70c0aebfb
  appKey: 72157720913745235-0965a563c267e289
  appSecret: 09f917d6329c5e1e

